# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWmGtsWhVrg-O31C0p12uBVtpyqsY-s5
"""

!pip install pandas

import pandas as pd
import numpy as np

"""### Pandas series"""

s= pd.Series()
print("pandas series:", s)
data=np.array(['g','e','e','k','s'])
s=pd.Series(data)
print("Pandas series\n",s)

"""### Pandas Dataframe  """

df=pd.DataFrame()
print(df)
lst=['greeks','for','abhishek','ansh','hardik pandya']
df=pd.DataFrame(lst)
print(df)

"""### creating a dataframe from a list of dictionaries"""

dict= {'name':["abhi","ansh","sunil"],'degree':["mba","ba","bcom"]}
df=pd.DataFrame(dict)
print(df)
print(df.index)


df_with_index =df.set_index('name')
print(df_with_index)

# reset the index back to the default integer index
df_reset=df.reset_index()
print(df_reset)

"""### accessing columns from DataFrame"""

dict= {'name':["abhi","ansh","sunil"],'degree':["mba","ba","bcom"]}
df=pd.DataFrame(dict)
print(df)
name = df['name']
print(name)

#access about row
second_row=df.iloc[1]
print(second_row)

# Access multiple row column
access_row_column = df.loc[1:2,['name','degree']]
print(access_row_column)

data= {'name':['abhi','karan','ansh','shagun','jai'],
               'age':[25,30,55,22,45],
               'gender':['male','male','male','female','male'],
               'salary':[500000,400000,55000,700000,400000]}
df= pd.DataFrame(data)
print(df)

#filter data
fliter_data = df[df['salary']>=400000]
print(fliter_data)

### to access specific data
specific_data = df.at[0,'name']
print(specific_data)

"""###Pandas series"""

import numpy as np
import pandas as pd

"""### we'all start analyzing " The Group of seven ". Which is a political formed by canada, France , Germany,italy , Japan , the united Kingdom and the united"""

# In millions
g7_pop =pd.Series([35.467 , 63.951 , 80.940 , 60.665 , 127.061 , 64.511 , 318.523])
print(g7_pop)

g7_pop.name = 'G7 Population in millions '
print(g7_pop)

g7_pop

g7_pop.dtype

g7_pop.values

type(g7_pop.values)

g7_pop[4]

g7_pop.index

### Indexing name Given to pandas series data
g7_pop.index= ['canada','France', 'germany' , 'italy',  'japan' ,'us','uk']

g7_pop

pd.Series({
    'Canada': 35.467,
    'France': 63.951,
    'Germany': 80.94,
    'Italy': 60.665,
    'Japan': 127.061,
    'United Kingdom': 64.511,
    'United States': 318.523
}, name='G7 Population in millions')

pd.Series(
    [35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523],
    index=['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom',
       'United States'],
    name='G7 Population in millions')

pd.Series(g7_pop, index=['France', 'germany', 'india','nepal',])

"""### Indexing"""

g7_pop['japan']

"""### Numeric positions can also be used , with the iloc attribute:"""

g7_pop.iloc[0]

g7_pop[['us','uk']]

g7_pop.iloc[[0,1,6]]

"""* We can also use slicing in pandas series.
* Importants Points : In Pandas, the upper Limit is also included

"""

g7_pop['canada' : 'italy']

"""### Conditional Selection ( Boolen arrays)
THe same boolean array techniques we saw applied to mumpy arrays can be used for PAndas series
"""

g7_pop

g7_pop>70

g7_pop[g7_pop>70]

g7_pop.mean()

g7_pop[g7_pop>g7_pop.mean()]

g7_pop.std()

g7_pop[(g7_pop > g7_pop.mean() - g7_pop.std()/2) | (g7_pop > g7_pop.mean()+ g7_pop.std()/2)]

"""### operations and method

### series also support vectorized operations and aggregation functions as numpy
"""

g7_pop

g7_pop + 100000

g7_pop.mean()

np.log(g7_pop)

g7_pop[ 'France' : 'italy'].mean()

g7_pop[(g7_pop>80)|(g7_pop<40)]

g7_pop[(g7_pop>80) & (g7_pop<200)]

"""## modifying series"""

g7_pop['canada'] = 40.5

g7_pop

g7_pop.iloc[-1] = 500
g7_pop

g7_pop[g7_pop<70]

g7_pop[g7_pop<70] = 99.99
g7_pop